# Generated by Django 5.1.2 on 2024-10-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
